/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/* Write to a bit band region, using bit band alias region */
static void bitBandWrite(uint32_t bitBandRegionAddr, uint8_t bitPos, uint8_t value)
{
	uint32_t* bitBandAliasRegionAddrPtr = NULL_PTR;
	uint32_t* bitBandRegionAddrPtr		= ((uint32_t*)bitBandRegionAddr);

	/* Check the input address is under the bit banding supported range, enter if it is true */
	if((bitBandRegionAddr >= BIT_BAND_REGION_BASE_ADDR) && (bitBandRegionAddr <= BIT_BAND_REGION_END_ADDR))
	{
		/* Calculate bit band alias region for given input address and bit position */
		bitBandAliasRegionAddrPtr = (uint32_t*)((BIT_BAND_ALIAS_REGION_BASE_ADDR)\
									+ (BIT_BAND_ALIAS_ADDR_EACH_BYTE_OFFSET * (bitBandRegionAddr - BIT_BAND_REGION_BASE_ADDR))\
									+ (BIT_BAND_ALIAS_ADDR_EACH_BIT_OFFSET * bitPos));

		/* Bit write for the given input address and bit position, using bit band alias address */
		*bitBandAliasRegionAddrPtr = value;

		/* Print bit band alias write is success, by checking the input given value is written to given input address and bit position */
		if(((*bitBandRegionAddrPtr >>  bitPos) & (LSB_BIT_MASK)) == (value & LSB_BIT_MASK))
		{
			printf("Bit band write is success for 0x%lX address in the %dth bit postion, using alias address %p\n",bitBandRegionAddr,bitPos,bitBandAliasRegionAddrPtr);
			printf("0x%X, is the given input value\n",value);
			printf("0x%lX, is the value at bit band region 0x%lX address in the %dth bit postion\n",\
					((*bitBandRegionAddrPtr >>  bitPos) & (LSB_BIT_MASK)),bitBandRegionAddr,bitPos);
			printf("0x%lX, is the value at bit band alias region %p address\n",(*bitBandAliasRegionAddrPtr & LSB_BIT_MASK),bitBandAliasRegionAddrPtr);

		}
		/* Print error message, if bit band alias write is failed */
		else
		{
			printf("Bit band write is failed\n");
		}
	}
	/* If input address is not supported bit band, throw error message */
	else
	{
		printf("This input address doesn't support bit band\n");
	}
	printf("\n");
}

/* Read from a bit band region, using bit band alias region */
static void bitBandRead(uint32_t bitBandRegionAddr, uint8_t bitPos, uint8_t* value)
{
	uint32_t* bitBandAliasRegionAddrPtr = NULL_PTR;
	uint32_t* bitBandRegionAddrPtr		= ((uint32_t*)bitBandRegionAddr);

	/* Check the input address is under the bit banding supported range, enter if it is true */
	if((bitBandRegionAddr >= BIT_BAND_REGION_BASE_ADDR) && (bitBandRegionAddr <= BIT_BAND_REGION_END_ADDR))
	{
		/* Calculate bit band alias region for given input address and bit position */
		bitBandAliasRegionAddrPtr = (uint32_t*)((BIT_BAND_ALIAS_REGION_BASE_ADDR)\
									+ (BIT_BAND_ALIAS_ADDR_EACH_BYTE_OFFSET * (bitBandRegionAddr - BIT_BAND_REGION_BASE_ADDR))\
									+ (BIT_BAND_ALIAS_ADDR_EACH_BIT_OFFSET * bitPos));

		/* Bit read for the given input address and bit position, using bit band alias address */
		*value = *bitBandAliasRegionAddrPtr;

		/* Print bit band alias Read is success, by checking the read value and the value in the given input address and bit position are same*/
		if(((*bitBandRegionAddrPtr >>  bitPos) & (LSB_BIT_MASK)) == (*value & LSB_BIT_MASK))
		{
			printf("Bit band Read is success for 0x%lX address in the %dth bit postion, using alias address %p\n",bitBandRegionAddr,bitPos,bitBandAliasRegionAddrPtr);
			printf("0x%X, is the read value\n",*value);
			printf("0x%lX, is the value at bit band region 0x%lX address in the %dth bit postion\n",\
					((*bitBandRegionAddrPtr >>  bitPos) & (LSB_BIT_MASK)),bitBandRegionAddr,bitPos);
			printf("0x%lX, is the value at bit band alias region %p address\n",(*bitBandAliasRegionAddrPtr & LSB_BIT_MASK),bitBandAliasRegionAddrPtr);
		}
		/* Print error message, if bit band alias Read is failed */
		else
		{
			printf("Bit band Read is failed\n");
		}
	}
	/* If input address is not supported bit band, throw error message */
	else
	{
		printf("This input address doesn't support bit band\n");
	}
	printf("\n");
}

int main(void)
{
	/* Input address should be within the bit band region range, which is from 0x2000_0000 to 0x200F_FFFF */

	uint8_t readValue;

	/* Input address should be within the bit band region range, which is from 0x2000_0000 to 0x200F_FFFF */
	/* Write the value "0x01" to the 4th bit of 0x20010000 address */
 	bitBandWrite(0x20010000UL,4,0x01);
 	/* Read the value from the 4th bit of 0x20010000 address */
	bitBandRead(0x20010000UL,4,&readValue);

	/* Input address should be within the bit band region range, which is from 0x2000_0000 to 0x200F_FFFF */
	/* Write the value "0x00" to the 4th bit of 0x20010000 address */
	bitBandWrite(0x20010000UL,4,0x00);
	/* Read the value from the 4th bit of 0x20010000 address */
	bitBandRead(0x20010000UL,4,&readValue);

	/* Input address should be within the bit band region range, which is from 0x2000_0000 to 0x200F_FFFF */
	/* Write the value "0xFF"[but while writing via bit banding only 0th bit will be written from "0xFF" which is "0x01"] to the 7th bit of 0x20010000 address */
	bitBandWrite(0x20010000UL,7,0xFF);
	/* Read the value from the 7th bit of 0x20010000 address */
	bitBandRead(0x20010000UL,7,&readValue);

	/* Input address should be within the bit band region range, which is from 0x2000_0000 to 0x200F_FFFF */
	/* Write the value "0x0E"[but while writing via bit banding only 0th bit will be written from "0x0E" which is "0x00"] to the 7th bit of 0x20010000 address */
	bitBandWrite(0x20010000UL,7,0x0E);
	/* Read the value from the 7th bit of 0x20010000 address */
	bitBandRead(0x20010000UL,7,&readValue);

    /* Loop forever */
	for(;;);
}
